version: '2'
services:
  database:
    image: "mysql"
    ports:
       - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_USER: gopherface
        MYSQL_PASSWORD: gopherface
        MYSQL_DATABASE: gopherfacedb
    volumes:
    - ./config/gfdbdump.sql:/docker-entrypoint-initdb.d
  webapp:
    depends_on:
        - database 
    build: .
    ports:
        - "8080:8080"
#  reverseproxy:
#    depends_on:
#        - webapp
#    image: "nginx"
#    volumes:
#        - ./deployments-config/docker-single-setup/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#        - "80:80"
